export const ProjectList = [
  {
    id: 1,
    title: "ArrayBuilder",
    code: "https://github.com/nikhila2001/array-builder",
    image: "/assets/images_of_projects/arrayBuilder.png",
    Demo: "https://nikhila2001.github.io/array-builder/",
    description:
      "It's a helpful tool for learning and practicing array manipulation in JavaScript.",
    technologies: "React.Js,Material UI",
    learnings: "Arrow-functions,useState-hook,custom-styling using makeStyles",
  },
  {
    id: 2,
    title: "TaskTracker",
    code: "https://github.com/nikhila2001/task-tracker-master",
    image: "/assets/images_of_projects/todo.png",
    Demo: "https://task-tracker-master.vercel.app/",
    description: "Simple todo app with delete task function",
    technologies: "React.Js,CSS",
    learnings: "React Hooks,Using props,Conditional-rendering",
  },
  {
    id: 3,
    title: "Form-Validation",
    code: "https://github.com/nikhila2001/form-validation",
    image: "/assets/images_of_projects/form.png",
    Demo: "https://nikhila2001.github.io/form-validation/",
    description: "Validates the form before submitting",
    technologies: "HTML5,CSS3,JavaScript",
    learnings: "Regular-Expressions",
  },
  {
    id: 4,
    title: "Calculator",
    code: "https://github.com/nikhila2001/calci/tree/main",
    image: "/assets/images_of_projects/calci.png",
    Demo: "https://nikhila2001.github.io/calci/",
    description: "Calculator with basic functions",
    technologies: "HTML5,CSS3,JavaScript",
    learnings: "CSS Grid,DOM Manipulation,JavaScript Classes and Objects",
  },
  {
    id: 5,
    title: "Vertical Slider",
    code: "https://github.com/nikhila2001/Vertical-slider",
    image: "/assets/images_of_projects/slider.png",
    Demo: "https://nikhila2001.github.io/Vertical-slider/",
    description: "Vertically slides the images beautifully",
    technologies: "HTML5,CSS3,JavaScript",
    learnings: "CSS positions,flex-box,CSS Transforms",
  },
  {
    id: 6,
    title: "Responsive static Web design",
    code: "https://github.com/nikhila2001/lifestyle",
    image: "/assets/images_of_projects/lifestyle.png",
    Demo: "https://nikhila2001.github.io/lifestyle/",
    description: "Static design of a lifestyle website",
    technologies: "HTML5,CSS3,Bootstrap5",
    learnings: "Bootstrap Grid classes,Responsive images",
  },
];
